export const UPDATE_CODE = 'UPDATE_CODE';  
export const REFRESH_SCREEN = 'REFRESH_SCREEN';
export const UPDATE_PARSE_CODE = "UPDATE_PARSE_CODE";
export const REFRESH_KONVA_GRAPH = 'REFRESH_KONVA_GRAPH';